branch: "master"
noCI: true
dryRun: false
npmPublish: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - [
      "@semantic-release/npm",
      { "npmPublish": true }
    ]